CREATE TABLE Account (
   ID BIGINT IDENTITY PRIMARY KEY NOT NULL,
   HOLDERNAME VARCHAR(256) NOT NULL,
   BALANCE DECIMAL NOT NULL,
   VERSION BIGINT NOT NULL
);

CREATE TABLE TransactionLog (
   ID BIGINT IDENTITY PRIMARY KEY NOT NULL,
   FROMID BIGINT NOT NULL,
   TOID BIGINT NOT NULL,
   AMOUNT DECIMAL NOT NULL,
   CREATED TIMESTAMP NOT NULL
);

ALTER TABLE TransactionLog ADD FOREIGN KEY (FROMID) REFERENCES Account(id);
ALTER TABLE TransactionLog ADD FOREIGN KEY (TOID) REFERENCES Account(id);